M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Wed 20 Sep 2023 09:52:40 -03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-20T09:52:40-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X128.8Y-68.0
X128.8Y-112.0
X170.8Y-68.0
X170.8Y-112.0
T0
M30
